### ISSUE TITLE
xml > json

### ISSUE THREAD

**Issue by Valamiro** [simevo/fatturapa-magento#5]
dovrebbe essere possibile in PHP costruire un array annidato tipo:
```
$fattura = array(
    "DatiTrasmissione" = array(
        "IdTrasmittente" = array(
            "IdPaese" => $store->merchant_country,
            ...
```
quindi convertirlo a JSON con
`$json = json_encode(array("FatturaElettronica" => $fattura), JSON_PRETTY_PRINT);`

**Comment by simevo** [comment]
vedi qui per un esempio che utilizza twig come templating engine server-side:
https://github.com/simevo/fattura-elettronica-json/blob/master/bin/json2xml.php

in alternativa si può eliminare la dipendenza da twig ed effettuare la conversione JSON->XML client side con il [template handlebars](https://github.com/simevo/fattura-elettronica-json/blob/master/fatturaPA_1.2.hbs) e questo snippet:
https://github.com/simevo/fattura-elettronica-json/blob/master/www/index.html#L52
